---
title: "About the Project"
author: "Chia You (Benson) Chou"
output: 
    html_document:
        toc: TRUE # table of content
        toc_float: TRUE
urlcolor: blue
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE)
library(dplyr)
library(plotly)
library(tidyr)
```

# Introduction
Growing up, it is common to hear my parent's talking about how much carat a diamond is and then proceeding to say it must be really expensive if they hear a high number. However, there are many more characteristics, such as the quality of the cut, color, clarity, table, and depth that can be taken account into when evaluating a diamond's value. 

For this report, I will be using data scraped from Brilliant Earth. 
[Brilliant Earth](https://www.brilliantearth.com/) is a well-known jewelry company that focuses on ethically sourced and sustainable diamonds, gemstones, and metals. They offer a wide range of engagement rings, wedding bands, and other jewelry that are not only stunning but also socially conscious. On their website, they display a table of available diamonds and their characteristics such as price, shape, carat, quality of the cut, color, clarity, depth, and table. (More details of variables will be discussed in next section)

# Research Question
In this report, I would like to investiage this question: What other qualities, besides from carat, influences a diamond's value the most? Do they have a positive or negative influence on a diamond's value?

# Access the Project
View the [complete pdf report](https://github.com/Benson-chou/JSC370-Final-Project/blob/main/JSC370-Final-Project-Report.pdf)

